const WS_EVENTS = Object.freeze({
  CONNECTED: 'CONNECTED',
  ALL_VEHICLES_STATE: 'ALL_VEHICLES_STATE',
  VEHICLE_UPDATE: 'VEHICLE_UPDATE',
  ALERT_FIRED: 'ALERT_FIRED',
  DEVICE_STATUS_CHANGE: 'DEVICE_STATUS_CHANGE'
});

const ALERT_TYPES = Object.freeze({
  SUSPECTED_FUEL_DROP: 'SUSPECTED_FUEL_DROP',
  LOW_FUEL: 'LOW_FUEL',
  OVERSPEED: 'OVERSPEED',
  DEVICE_STALE: 'DEVICE_STALE',
  DEVICE_OFFLINE: 'DEVICE_OFFLINE',
  DOOR_OPEN_PARKED: 'DOOR_OPEN_PARKED',
  REFILL_DETECTED: 'REFILL_DETECTED',
  GEOFENCE_VIOLATION: 'GEOFENCE_VIOLATION',
  DRIVER_VIOLATION: 'DRIVER_VIOLATION'
});

const ALERT_SEVERITY = Object.freeze({
  INFO: 'info',
  WARNING: 'warning',
  CRITICAL: 'critical'
});

const DEVICE_STATUS = Object.freeze({
  ONLINE: 'online',
  STALE: 'stale',
  OFFLINE: 'offline'
});

const ERROR_CODES = Object.freeze({
  INVALID_PAYLOAD: 'INVALID_PAYLOAD',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  MISSING_TOKEN: 'MISSING_TOKEN',
  INVALID_TOKEN: 'INVALID_TOKEN',
  UNKNOWN_DEVICE: 'UNKNOWN_DEVICE',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  DUPLICATE_VEHICLE_ID: 'DUPLICATE_VEHICLE_ID',
  DUPLICATE_DEVICE_ID: 'DUPLICATE_DEVICE_ID',
  DUPLICATE_LICENSE: 'DUPLICATE_LICENSE',
  INTERNAL_ERROR: 'INTERNAL_ERROR'
});

export {
  WS_EVENTS,
  ALERT_TYPES,
  ALERT_SEVERITY,
  DEVICE_STATUS,
  ERROR_CODES
};
